version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3336:3306"  # map port 3306 trong container ra 3336 trên máy host
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: springboot-rhymcaffer
    ports:
      - "${PORT}:8080"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  mysql_data: