server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rhymcaffer?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:test-password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:test-secret}
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    bui.dev.rhymcaffer: DEBUG
